### **1. Load Dependencies**

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sentence_transformers import SentenceTransformer
import mlflow

E:\ML\RoadMap\Log-Classification-Hybrid-Framework\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### **2. Load Data**

In [2]:
df = pd.read_csv("training/datasets/synthetic_logs.csv")
df

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert
...,...,...,...,...,...
2405,2025-08-13 07:29:25,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert
2406,1/11/2025 5:32,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert
2407,2025-08-03 03:07:47,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert
2408,11/11/2025 11:52,BillingSystem,Email service affected by failed transmission,Critical Error,bert
2409,12/25/2025 13:21,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert

In [3]:
df = df.drop('timestamp',axis=1)

In [4]:
df.head()

,source,log_message,target_label,complexity
0,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
2,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert
3,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert
4,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert

### **3. Preprocessing**

#### **3.1 Handle Missing values**

In [5]:
df.isnull().sum()

source          0
log_message     0
target_label    0
complexity      0
dtype: int64

#### **3.2 Handle wrong format values**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2410 entries, 0 to 2409
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   source        2410 non-null   object
 1   log_message   2410 non-null   object
 2   target_label  2410 non-null   object
 3   complexity    2410 non-null   object
dtypes: object(4)
memory usage: 75.4+ KB

In [7]:
#### WE WILL CREATE EMBEDDINGS FOR THE LOG_MESSAGE COLUMN

# 1. Load a pretrained Sentence Transformer model
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")


# 2. Calculate embeddings by calling model.encode()
embeddings = model.encode(df['log_message'].tolist())
print(embeddings.shape)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 103/103 [00:00<00:00, 4652.61it/s]

(2410, 384)

In [8]:
embeddings[:1]

array([[-1.02939621e-01,  3.35459262e-02, -2.20260601e-02,
         1.55105593e-03, -9.86920949e-03, -1.78956255e-01,
        -6.34409785e-02, -6.01761676e-02,  2.81108841e-02,
         5.99620454e-02, -1.72618646e-02,  1.43367471e-03,
        -1.49560004e-01,  3.15285777e-03, -5.66031076e-02,
         2.71685384e-02, -1.49890380e-02, -3.54037546e-02,
        -3.62936258e-02, -1.45410234e-02, -5.61493542e-03,
         8.75539109e-02,  4.55120429e-02,  2.50963680e-02,
         1.00187706e-02,  1.24267014e-02, -1.39923617e-01,
         7.68696442e-02,  3.14095207e-02, -4.15248703e-03,
         4.36902680e-02,  1.71250310e-02, -8.00951496e-02,
         5.74005917e-02,  1.89091805e-02,  8.55262280e-02,
         3.96399237e-02, -1.34371832e-01, -1.44364929e-03,
         3.06707853e-03,  1.76854029e-01,  4.44886740e-03,
        -1.69275180e-02,  2.24266723e-02, -4.35049348e-02,
         6.09028572e-03, -9.98169184e-03, -6.23973049e-02,
         1.07372776e-02, -6.04895549e-03, -7.14660808e-02,
        -8.45804159e-03, -3.18019725e-02, -1.00518368e-01,
         2.25874610e-04, -1.89341344e-02, -3.17793936e-02,
         4.00861464e-02,  2.19178386e-02, -2.59528793e-02,
         5.84525056e-02, -8.12509879e-02,  2.12029237e-02,
        -5.02687208e-02,  1.32057238e-02,  1.32673979e-03,
         2.27062777e-02, -3.45793962e-02,  3.91546935e-02,
        -2.09433753e-02,  3.24825617e-03,  4.43960838e-02,
        -9.85358059e-02, -2.88895629e-02, -6.85024215e-03,
         5.38819209e-02,  6.46110326e-02, -2.45060753e-02,
         9.21829194e-02, -7.49868751e-02,  1.23994844e-02,
        -1.00026600e-01, -4.64910865e-02,  6.01570010e-02,
        -2.46480517e-02, -7.08075836e-02, -2.77270488e-02,
         9.72610936e-02,  3.85841578e-02, -1.44292917e-02,
        -7.46868434e-04, -1.04305176e-02, -1.61842629e-02,
         4.43628393e-02,  9.25998390e-03,  7.14165419e-02,
         6.37917221e-02,  4.94930781e-02, -6.02567531e-02,
         4.04805616e-02, -3.42860632e-02, -1.93880890e-02,
         6.61234111e-02,  6.01589456e-02,  1.09371357e-02,
        -5.38631110e-03,  1.44579792e-02,  9.25429538e-02,
        -3.14564072e-02, -1.84351932e-02,  9.91874002e-03,
        -1.85574181e-02,  1.31283526e-03,  2.26565789e-05,
         2.02737004e-03,  2.75256615e-02, -4.81927805e-02,
         5.42826280e-02, -7.32067227e-02,  4.88666818e-02,
         4.98490296e-02, -9.01146419e-03, -4.68905903e-02,
        -4.25886884e-02, -8.19523707e-02,  3.87106203e-02,
         7.85503387e-02,  1.46077067e-32,  1.66706219e-02,
         5.25494032e-02, -1.82448924e-02, -1.26686301e-02,
         6.52837306e-02, -2.11777389e-02, -4.06322964e-02,
         4.14947681e-02, -2.48361211e-02, -1.33068226e-02,
        -5.46753407e-02, -5.99099207e-04, -4.89247590e-03,
        -6.27359450e-02, -3.84878330e-02, -6.13543727e-02,
         8.27405378e-02,  2.34380066e-02, -8.63090251e-03,
         1.31002637e-02,  6.44214749e-02, -4.41361777e-02,
        -6.98633268e-02, -7.36060441e-02, -4.33263555e-02,
         6.96525304e-03, -5.05956747e-02, -1.60911661e-02,
        -5.66794276e-02,  3.35453451e-03,  5.34115285e-02,
         2.47761346e-02, -1.47985918e-02, -2.93243062e-02,
         7.30227754e-02, -1.86833795e-02,  8.13137367e-02,
        -2.69967522e-02, -5.68056293e-02, -6.59389049e-02,
        -5.95393917e-03,  2.85312869e-02, -7.85358176e-02,
        -2.76699569e-03, -3.26464605e-03, -9.28332955e-02,
        -7.27362633e-02, -3.31903398e-02,  1.01411104e-01,
         9.79881883e-02, -9.78740379e-02,  1.98667776e-02,
         2.38837004e-02, -1.81672703e-02, -3.73708978e-02,
         1.96550880e-03,  6.34425879e-02,  1.18271634e-02,
        -1.12041244e-02, -3.87316197e-02,  9.32424366e-02,
         4.26632818e-03, -1.66872665e-02, -6.87464178e-02,
         1.55120259e-02, -4.97755297e-02,  3.34492996e-02,
         8.00032169e-02,  2.12282110e-02,  1.34581894e-01,
        -2.30729748e-02,  5.53859174e-02,  3.07558328e-02,
        -2.93905865e-02,  2.31905635e-02, -9.34307724e-02,
         7.58034661e-02, -5.21202292e-03, -5.14522903e-02,
         3.32689062e-02,  3.67963016e-02, -1.06450412e-02,
         1.01634767e-02, -2.07650978e-02, -5.85518815e-02,
         4.79328893e-02,  2.13694740e-02,  8.76213312e-02,
         3.35493986e-03, -3.80336083e-02, -1.81204882e-02,
         6.87447097e-03,  5.15879579e-02, -4.75598797e-02,
        -6.12065308e-02, -1.45483574e-32,  4.12795413e-03,
         4.59641824e-03, -5.63900769e-02,  4.32464061e-03,
        -1.09443453e-03,  9.31954663e-03, -2.20269114e-02,
         5.79564087e-02, -1.44787710e-02,  4.64155376e-02,
         1.43542886e-01, -6.89756870e-02,  6.09631725e-02,
        -8.93743932e-02,  2.40919460e-02,  2.06010323e-02,
        -2.82415953e-02, -6.48315176e-02,  5.64795323e-02,
        -7.48338271e-03, -3.52057926e-02,  8.51060599e-02,
         1.30359884e-02,  2.02257950e-02, -1.44391255e-02,
        -4.63718884e-02,  1.77209806e-02,  1.59106031e-02,
        -9.51009542e-02, -3.54527272e-02,  2.08696630e-02,
         3.84387863e-03, -8.77918378e-02,  6.44575357e-02,
         1.44171370e-02,  3.84723651e-03,  4.70991433e-02,
         4.94661406e-02,  1.53862843e-02, -2.59578750e-02,
         9.10894573e-02,  1.83308143e-02, -5.89206405e-02,
         2.51992792e-02, -3.30374166e-02,  8.23345259e-02,
         1.74792428e-02,  6.48047477e-02, -1.19673871e-02,
        -3.31778564e-02,  3.00177578e-02,  3.54219861e-02,
        -1.39624579e-02,  6.69272766e-02,  3.87919955e-02,
         6.06916845e-02,  1.17958989e-03, -2.38786563e-02,
        -1.26930445e-01,  1.13846660e-02,  1.59290414e-02,
        -1.29426736e-02, -8.63247812e-02,  8.53662658e-03,
         6.03761338e-02,  1.51122119e-02, -1.19132333e-01,
         1.15234861e-02,  5.97089604e-02, -3.93345505e-02,
         1.55673418e-02,  1.04602138e-02, -4.72456478e-02,
        -2.59243418e-02,  9.98527370e-03,  3.07146609e-02,
        -7.14844838e-02,  6.98959501e-03, -1.55133503e-02,
         2.18864009e-02, -2.78145876e-02,  6.92733303e-02,
        -2.75903624e-02,  2.62429751e-02,  3.52562405e-02,
        -4.26419862e-02,  7.46298814e-04,  6.59866631e-02,
        -5.15105203e-02, -3.58434021e-02, -6.53444603e-03,
        -2.75858529e-02, -1.00125574e-01,  7.83326104e-02,
        -1.45799220e-02, -6.18457250e-08,  2.00325232e-02,
         6.59784973e-02, -2.04702578e-02,  1.64043885e-02,
         7.63001516e-02,  7.32182786e-02,  5.65787544e-03,
        -6.97790470e-04, -3.63798812e-03,  6.02394082e-02,
        -3.27187367e-02, -6.45838231e-02, -5.97952306e-02,
        -1.76695883e-02,  6.10143412e-03, -5.63489553e-03,
        -1.22972235e-01,  6.35819137e-02, -2.19431706e-02,
        -1.16406485e-01,  2.34365929e-02, -7.23525360e-02,
         2.31774058e-02, -6.55986965e-02, -7.42681548e-02,
         2.60146186e-02,  3.59758884e-02,  7.68432766e-02,
        -3.08057107e-02, -2.34793983e-02, -6.30426332e-02,
        -3.62158045e-02, -1.03559690e-02, -4.75602336e-02,
        -2.87522171e-02,  2.96400841e-02, -5.26892301e-03,
         5.67890443e-02, -3.74488020e-03,  3.09612583e-02,
         3.48227173e-02,  3.78607772e-02,  2.10155919e-02,
         2.70691644e-02,  5.25520295e-02,  7.16229454e-02,
        -5.53757790e-03,  4.01093848e-02,  5.16276918e-02,
        -2.67314892e-02,  5.94224259e-02, -4.29224260e-02,
        -1.19760474e-02,  3.05985250e-02, -7.40331709e-02,
         1.84221957e-02, -8.64865351e-03, -8.83557275e-02,
        -5.91984242e-02, -1.00890356e-04,  1.12913623e-01,
         4.57791239e-03, -4.25971746e-02,  3.22620920e-03]], dtype=float32)

#### **3.3 Handle wrong values**

#### **3.4 Handle duplicates**

### **4. Model Building**

#### **4.1 We will use unsupervised models to identify the patterns**

In [9]:
from sklearn.cluster import DBSCAN # DBSCAN is a algo like KMeans clustering

uns_model = DBSCAN(eps=0.2,min_samples=5,metric='cosine')

clusters = uns_model.fit_predict(embeddings)

df['cluster'] = clusters
df.head()

,source,log_message,target_label,complexity,cluster
0,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0
1,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
2,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,-1
3,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0
4,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0

In [10]:
df.target_label.unique()

array(['HTTP Status', 'Critical Error', 'Security Alert', 'Error',
       'System Notification', 'Resource Usage', 'User Action',
       'Workflow Error', 'Deprecation Warning'], dtype=object)

In [11]:
df.cluster.unique()

array([ 0,  1, -1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 19, 13, 14,
       15, 16, 17, 18, 22, 20, 21, 26, 25, 23, 24, 30, 31, 27, 28, 29],
      dtype=int64)

In [12]:
cluster_counts = df.cluster.value_counts()
large_clusters = cluster_counts[cluster_counts>10].index


for cluster in large_clusters:
    print(f"Cluster {cluster} :")
    print(df[df['cluster']==cluster]['log_message'].head(5))
    print()

Cluster 0 :
0    nova.osapi_compute.wsgi.server [req-b9718cd8-f...
3    nova.osapi_compute.wsgi.server [req-4895c258-b...
4    nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...
5    nova.osapi_compute.wsgi.server [req-f0bffbc3-5...
9    nova.osapi_compute.wsgi.server [req-2bf7cfee-a...
Name: log_message, dtype: object

Cluster -1 :
2             Unauthorized access to data was attempted
34    Suspicious login activity detected from 192.16...
43    Abnormal system behavior on server 40, potenti...
51    Server 4 restarted without warning during data...
55    Server 34 crashed unexpectedly while syncing data
Name: log_message, dtype: object

Cluster 4 :
8     nova.compute.claims [req-a07ac654-8e81-416d-bf...
26    nova.compute.claims [req-d6986b54-3735-4a42-90...
40    nova.compute.claims [req-72b4858f-049e-49e1-b3...
58    nova.compute.claims [req-5c8f52bd-8e3c-41f0-95...
61    nova.compute.claims [req-d38f479d-9bb9-4276-96...
Name: log_message, dtype: object

Cluster 10 :
27     User User685 logged out.
57      User User395 logged in.
85      User User225 logged in.
88     User User494 logged out.
126     User User900 logged in.
Name: log_message, dtype: object

Cluster 12 :
30     Backup started at 2025-05-14 07:06:55.
44     Backup started at 2025-02-15 20:00:19.
108      Backup ended at 2025-08-08 13:06:23.
128    Backup started at 2025-11-14 08:27:43.
191    Backup started at 2025-12-09 10:19:11.
Name: log_message, dtype: object

Cluster 6 :
13     Multiple bad login attempts detected on user 8...
53     Multiple login failures occurred on user 9052 ...
72      User 7153 made multiple incorrect login attempts
74      User 8300 made multiple incorrect login attempts
113    Multiple login failures were detected for user...
Name: log_message, dtype: object

Cluster 7 :
15    Backup completed successfully.
52    Backup completed successfully.
54    Backup completed successfully.
81    Backup completed successfully.
83    Backup completed successfully.
Name: log_message, dtype: object

Cluster 17 :
50     System updated to version 3.9.1.
176    System updated to version 5.5.4.
185    System updated to version 4.7.4.
192    System updated to version 3.7.7.
260    System updated to version 2.6.2.
Name: log_message, dtype: object

Cluster 2 :
6              Shard 6 replication task ended in failure
45     Data replication task for shard 14 did not com...
98             Data replication task failed for shard 17
104               Replication of data to shard 14 failed
190    Data replication task for shard 6 did not comp...
Name: log_message, dtype: object

Cluster 3 :
7      File data_6169.csv uploaded successfully by us...
14     File data_3847.csv uploaded successfully by us...
48     File data_7366.csv uploaded successfully by us...
129    File data_1206.csv uploaded successfully by us...
194    File data_1503.csv uploaded successfully by us...
Name: log_message, dtype: object

Cluster 21 :
96     Disk cleanup completed successfully.
160    Disk cleanup completed successfully.
208    Disk cleanup completed successfully.
225    Disk cleanup completed successfully.
252    Disk cleanup completed successfully.
Name: log_message, dtype: object

Cluster 5 :
11       Critical system unit error: unit ID Component55
35     System component malfunction: component ID Com...
115    Critical system element is down: element ID Co...
175    Essential system part malfunction: part ID Com...
204    Failure occurred in critical system component:...
Name: log_message, dtype: object

Cluster 13 :
36     System reboot initiated by user User243.
92     System reboot initiated by user User471.
139    System reboot initiated by user User216.
140    System reboot initiated by user User639.
161    System reboot initiated by user User819.
Name: log_message, dtype: object

Cluster 14 :
38     Denied access attempt on restricted account Ac...
200      Account Account9437 blocked due to failed login
206    Account Account7999 access denied due to login...
306    Invalid login attempt made on secured account ...
409    Account Account8057 login attempt was not succ...
Name: log_message, dtype: object

Cluster 8 :
18     Account with ID 5351 created by User634.
122    Account with ID 7813 created by User373.
205    Account with ID 9827 created by User965.
259    Account with ID 2520 created by User546.
273    Account with ID 2300 created by User964.
Name: log_message, dtype: object

Cluster 16 :
46       User 7662 tried to bypass API security measures
159    User 2367 failed to provide valid API access c...
229           User 3569 made an unauthorized API request
279    Unauthorized user 2968 tried to access restric...
368    User 2186 attempted to access API without prop...
Name: log_message, dtype: object

Cluster 1 :
1        Email service experiencing issues with sending
10             Email server encountered a sending fault
217          Mail service encountered a delivery glitch
248    Service disruption caused by email sending error
265           Email system had a problem sending emails
Name: log_message, dtype: object

Cluster 9 :
22     nova.compute.resource_tracker [req-addc1839-2e...
82     nova.compute.resource_tracker [req-addc1839-2e...
120    nova.compute.resource_tracker [req-addc1839-2e...
153    nova.compute.resource_tracker [req-addc1839-2e...
238    nova.compute.resource_tracker [req-addc1839-2e...
Name: log_message, dtype: object

Cluster 23 :
282    Service health check was not successful becaus...
528    Invalid SSL certificate resulted in a failed s...
545    Service health check failure was due to an inv...
601    An issue with the SSL certificate caused the s...
734    Service health check failure was caused by an ...
Name: log_message, dtype: object

Cluster 24 :
283    Module X experienced an invalid data format issue
344           Input format mismatch occurred in module X
378    Module X reported an error in input format val...
454    Module X failed to process input due to format...
530    Input data format in module X was invalid or c...
Name: log_message, dtype: object

Cluster 19 :
32       Detection of multiple disk faults in RAID setup
69      RAID array suffered multiple hard drive failures
102         RAID array experienced multiple disk crashes
223    Multiple hard drive issues in RAID configurati...
300    Identification of multiple faulty disks in RAI...
Name: log_message, dtype: object

Cluster 15 :
42      Boot process terminated unexpectedly due to ke...
416     System encountered kernel panic during initial...
827        Boot process was stopped by kernel malfunction
956     System encountered kernel failure during bootu...
1073             Boot sequence failed due to kernel panic
Name: log_message, dtype: object

Cluster 18 :
62              System configuration is no longer valid
453    Configuration is corrupted throughout the system
578         Cross-system configuration failure occurred
731         System configuration is experiencing errors
917            Configuration malfunction is system-wide
Name: log_message, dtype: object

Cluster 28 :
421        Admin privilege escalation alert for user 2893
747        Admin privilege escalation alert for user 8532
904     Potential security threat: Admin privilege esc...
1334    Warning: Potential admin privilege escalation ...
1452    Alert: Admin privilege escalation for user 685...
Name: log_message, dtype: object

In [13]:
import re
def classify_with_regex(log_message):
    regex_patterns = {
        r"User User\d+ logged (out|in)." : "User Action",
        r"Account with ID .* created by .*.": "User Action",
        r"Backup (started|ended) at .*":"System Notification",
        r"Backup completed successfully.": "System Notification",
        r"System updated to version .*": "System Notification",
        r"File .* uploaded successfully by user .*":"System Notification",
        r"Disk cleanup completed successfully.":"System Notification",
        r"System reboot initiated by user User.*":"System Notification",
    }

    for regex_pattern,label in regex_patterns.items():
        if re.search(regex_pattern,log_message):
            return label
    return None

msgs = [
"User User685 logged out.",
"User User395 logged in.",
"Backup started at 2025-02-15 20:00:19."
"Backup ended at 2025-08-08 13:06:23",
"Backup completed successfully.",
"File data_1206.csv uploaded successfully by user ..."
"File data_1503.csv uploaded successfully by user sdf",
"Disk cleanup completed successfully.",
"System reboot initiated by user User471.",
"Account with ID 2520 created by User546.",
'nova.osapi_compute.wsgi.server [req-b9718cd8-f65e-49cc-8349-6cf7122af137 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" status: 200 len: 1893 time: 0.2675118	HTTP Status	bert	0'
]
for msg in msgs:
    print(msg,classify_with_regex(msg))

User User685 logged out. User Action
User User395 logged in. User Action
Backup started at 2025-02-15 20:00:19.Backup ended at 2025-08-08 13:06:23 System Notification
Backup completed successfully. System Notification
File data_1206.csv uploaded successfully by user ...File data_1503.csv uploaded successfully by user sdf System Notification
Disk cleanup completed successfully. System Notification
System reboot initiated by user User471. System Notification
Account with ID 2520 created by User546. User Action
nova.osapi_compute.wsgi.server [req-b9718cd8-f65e-49cc-8349-6cf7122af137 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" status: 200 len: 1893 time: 0.2675118	HTTP Status	bert	0 None

In [14]:
largest_clusters = cluster_counts[:4].index  # this include the cluster with the most num of elements after clustering

for cluster in largest_clusters:
    print(f"Cluster {cluster} :")
    print(df[df['cluster']==cluster]['log_message'].head(5))
    print()

Cluster 0 :
0    nova.osapi_compute.wsgi.server [req-b9718cd8-f...
3    nova.osapi_compute.wsgi.server [req-4895c258-b...
4    nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...
5    nova.osapi_compute.wsgi.server [req-f0bffbc3-5...
9    nova.osapi_compute.wsgi.server [req-2bf7cfee-a...
Name: log_message, dtype: object

Cluster -1 :
2             Unauthorized access to data was attempted
34    Suspicious login activity detected from 192.16...
43    Abnormal system behavior on server 40, potenti...
51    Server 4 restarted without warning during data...
55    Server 34 crashed unexpectedly while syncing data
Name: log_message, dtype: object

Cluster 4 :
8     nova.compute.claims [req-a07ac654-8e81-416d-bf...
26    nova.compute.claims [req-d6986b54-3735-4a42-90...
40    nova.compute.claims [req-72b4858f-049e-49e1-b3...
58    nova.compute.claims [req-5c8f52bd-8e3c-41f0-95...
61    nova.compute.claims [req-d38f479d-9bb9-4276-96...
Name: log_message, dtype: object

Cluster 10 :
27     User User685 logged out.
57      User User395 logged in.
85      User User225 logged in.
88     User User494 logged out.
126     User User900 logged in.
Name: log_message, dtype: object

In [15]:
df['regex_label'] = df['log_message'].apply(lambda x: classify_with_regex(x))
df

,source,log_message,target_label,complexity,cluster,regex_label
0,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0,None
1,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,None
2,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,-1,None
3,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0,None
4,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0,None
...,...,...,...,...,...,...
2405,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert,0,None
2406,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert,6,None
2407,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert,0,None
2408,BillingSystem,Email service affected by failed transmission,Critical Error,bert,1,None
2409,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert,6,None

In [16]:
df['regex_label'].notnull().sum()

500

In [17]:
# We have successfully classified 500 out of 2k notifications
df_no_regex = df[df['regex_label'].isnull()]
df_no_regex

,source,log_message,target_label,complexity,cluster,regex_label
0,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0,None
1,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,None
2,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,-1,None
3,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0,None
4,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0,None
...,...,...,...,...,...,...
2405,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert,0,None
2406,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert,6,None
2407,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert,0,None
2408,BillingSystem,Email service affected by failed transmission,Critical Error,bert,1,None
2409,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert,6,None

In [18]:
# lets check all the clusters containing User Action and system notification are missing in the df_no_regex (3,7,8,10,12,13,21) 
df_no_regex.cluster.unique()

array([ 0,  1, -1,  2,  4,  5,  6,  9, 11, 19, 14, 15, 16, 18, 22, 20, 26,
       25, 23, 24, 30, 31, 27, 28, 29], dtype=int64)

In [19]:
# great classfiy with regex have done its job
# no we will have to do classification with a model
# client said that log_messages with source LegacyCRM have few messages. so we will classify them using an LLM.Therefore we will make a new dataset without LegacyCRM to train the model
df_no_legacy =  df_no_regex[df_no_regex.source != "LegacyCRM"]
df_no_legacy

,source,log_message,target_label,complexity,cluster,regex_label
0,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0,None
1,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,None
2,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,-1,None
3,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0,None
4,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0,None
...,...,...,...,...,...,...
2405,ModernHR,nova.osapi_compute.wsgi.server [req-96c3ec98-2...,HTTP Status,bert,0,None
2406,ModernHR,User 3844 account experienced multiple failed ...,Security Alert,bert,6,None
2407,ThirdPartyAPI,nova.metadata.wsgi.server [req-b6d4a270-accb-4...,HTTP Status,bert,0,None
2408,BillingSystem,Email service affected by failed transmission,Critical Error,bert,1,None
2409,AnalyticsEngine,Repeated failed login attempts occurred for us...,Security Alert,bert,6,None

In [20]:
df_no_legacy.source.unique()

array(['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem',
       'ThirdPartyAPI'], dtype=object)

In [21]:
# successfully removed LegacyCRM rows.
df_no_legacy.cluster.unique()

array([ 0,  1, -1,  2,  4,  5,  6,  9, 11, 19, 14, 15, 16, 18, 22, 20, 26,
       25, 23, 24, 30, 31, 27, 28, 29], dtype=int64)

In [22]:
df_no_legacy.target_label.unique()

array(['HTTP Status', 'Critical Error', 'Security Alert', 'Error',
       'Resource Usage'], dtype=object)

In [23]:
# in a real life scenario we will have to select which cluster belong to which category.
encoder = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

X = encoder.encode(df_no_legacy['log_message'].to_list())
y = df_no_legacy['target_label']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)

Loading weights: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 103/103 [00:00<00:00, 6866.51it/s]

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB,GaussianNB


model_params = {
    
        'svm':{
            'model':SVC(),
            'params':{
                'C':[1,2,3,4,5,7,10,11],
                'kernel':['linear', 'poly', 'rbf', 'sigmoid']
            }
        },

        'random_forest':{
            'model':RandomForestClassifier(),
            'params':{
                'n_estimators':[30,40,50,100,120,150],
                'criterion': ['gini', 'entropy', 'log_loss'],
            }
        },
        'logistic_regression':{
            'model':LogisticRegression(),
            'params':{
                'C':[1,2,3,4,5,6,7,10,11],
                'solver':['lbfgs', 'newton-cg', 'newton-cholesky', 'sag', 'saga'],
            }
        },     
        'gaussian_nb':{
            'model':GaussianNB(),
            'params':{
                'priors':[None],
                'var_smoothing': [1e-9]
            }
        },
}

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

analytics = []
for model_name,mp in model_params.items():
    clf = GridSearchCV(estimator=mp['model'],param_grid=mp['params'],cv=5,return_train_score=False)
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    report = classification_report(y_test,y_pred,output_dict=True)
    tmp = [model_name,clf.best_params_,clf.best_score_,clf,report]
    analytics.append(tmp)

In [30]:
analytics

[['svm',
  {'C': 2, 'kernel': 'poly'},
  0.9984990566303399,
  GridSearchCV(cv=5, estimator=SVC(),
               param_grid={'C': [1, 2, 3, 4, 5, 7, 10, 11],
                           'kernel': ['linear', 'poly', 'rbf', 'sigmoid']}),
  {'Critical Error': {'precision': 0.9795918367346939,
    'recall': 1.0,
    'f1-score': 0.9896907216494846,
    'support': 48.0},
   'Error': {'precision': 1.0,
    'recall': 0.9787234042553191,
    'f1-score': 0.989247311827957,
    'support': 47.0},
   'HTTP Status': {'precision': 1.0,
    'recall': 1.0,
    'f1-score': 1.0,
    'support': 304.0},
   'Resource Usage': {'precision': 1.0,
    'recall': 1.0,
    'f1-score': 1.0,
    'support': 49.0},
   'Security Alert': {'precision': 1.0,
    'recall': 1.0,
    'f1-score': 1.0,
    'support': 123.0},
   'accuracy': 0.9982486865148862,
   'macro avg': {'precision': 0.9959183673469388,
    'recall': 0.9957446808510639,
    'f1-score': 0.9957876066954883,
    'support': 571.0},
   'weighted avg': {'precision': 0.9982844276064191,
    'recall': 0.9982486865148862,
    'f1-score': 0.9982482982400863,
    'support': 571.0}}],
 ['random_forest',
  {'criterion': 'log_loss', 'n_estimators': 120},
  0.9969981132606798,
  GridSearchCV(cv=5, estimator=RandomForestClassifier(),
               param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                           'n_estimators': [30, 40, 50, 100, 120, 150]}),
  {'Critical Error': {'precision': 0.9411764705882353,
    'recall': 1.0,
    'f1-score': 0.9696969696969697,
    'support': 48.0},
   'Error': {'precision': 0.9777777777777777,
    'recall': 0.9361702127659575,
    'f1-score': 0.9565217391304348,
    'support': 47.0},
   'HTTP Status': {'precision': 1.0,
    'recall': 1.0,
    'f1-score': 1.0,
    'support': 304.0},
   'Resource Usage': {'precision': 1.0,
    'recall': 1.0,
    'f1-score': 1.0,
    'support': 49.0},
   'Security Alert': {'precision': 1.0,
    'recall': 0.991869918699187,
    'f1-score': 0.9959183673469387,
    'support': 123.0},
   'accuracy': 0.9929947460595446,
   'macro avg': {'precision': 0.9837908496732026,
    'recall': 0.9856080262930289,
    'f1-score': 0.9844274152348685,
    'support': 571.0},
   'weighted avg': {'precision': 0.9932259652255532,
    'recall': 0.9929947460595446,
    'f1-score': 0.9929946330442354,
    'support': 571.0}}],
 ['logistic_regression',
  {'C': 3, 'solver': 'lbfgs'},
  0.9969981132606798,
  GridSearchCV(cv=5, estimator=LogisticRegression(),
               param_grid={'C': [1, 2, 3, 4, 5, 6, 7, 10, 11],
                           'solver': ['lbfgs', 'newton-cg', 'newton-cholesky',
                                      'sag', 'saga']}),
  {'Critical Error': {'precision': 0.9056603773584906,
    'recall': 1.0,
    'f1-score': 0.9504950495049505,
    'support': 48.0},
   'Error': {'precision': 1.0,
    'recall': 0.8936170212765957,
    'f1-score': 0.9438202247191011,
    'support': 47.0},
   'HTTP Status': {'precision': 1.0,
    'recall': 1.0,
    'f1-score': 1.0,
    'support': 304.0},
   'Resource Usage': {'precision': 1.0,
    'recall': 1.0,
    'f1-score': 1.0,
    'support': 49.0},
   'Security Alert': {'precision': 1.0,
    'recall': 1.0,
    'f1-score': 1.0,
    'support': 123.0},
   'accuracy': 0.9912434325744308,
   'macro avg': {'precision': 0.9811320754716981,
    'recall': 0.9787234042553191,
    'f1-score': 0.9788630548448104,
    'support': 571.0},
   'weighted avg': {'precision': 0.992069523840994,
    'recall': 0.9912434325744308,
    'f1-score': 0.9912142082977853,
    'support': 571.0}}],
 ['gaussian_nb',
  {'priors': None, 'var_smoothing': 1e-09},
  0.9804736560502378,
  GridSearchCV(cv=5, estimator=GaussianNB(),
               param_grid={'priors': [None], 'var_smoothing': [1e-09]}),
  {'Critical Error': {'precision': 0.8571428571428571,
    'recall': 1.0,
    'f1-score': 0.9230769230769231,
    'support': 48.0},
   'Error': {'precision': 0.8297872340425532,
    'recall': 0.8297872340425532,
    'f1-score': 0.8297872340425532,
    'support': 47.0},
   'HTTP Status': {'precision': 1.0,
    'recall': 0.9736842105263158,
    'f1-score': 0.9866666666666667,
    'support': 304.0},
   'Resource Usage': {'precision': 1.0,
    'recall': 1.0,
    'f1-score': 1.0,
    'support': 49.0},
   'Security Alert': {'precision': 0.991869918699187,
    'recall': 0.991869918699187,
    'f1-score': 0.991869918699187,
    'support': 123.0},
   'accuracy': 0.9702276707530648,
   'macro avg': {'precision': 0.9357600019769194,
    'recall': 0.9590682726536113,
    'f1-score': 0.946280148497066,
    'support': 571.0},
   'weighted avg': {'precision': 0.9722291718789091,
    'recall': 0.9702276707530648,
    'f1-score': 0.9706731330549194,
    'support': 571.0}}]]

In [32]:
no_legacy_target_cls = df_no_legacy.target_label.unique()

In [37]:
import mlflow

mlflow.set_experiment('Log_Classification')
mlflow.set_tracking_uri('http://localhost:5000')

for ex in analytics:
    with mlflow.start_run(run_name=ex[0]):
        mlflow.log_param('model',ex[0])
        mlflow.log_params(ex[1])
        mlflow.log_metric('accuracy',ex[2])
        for clz in no_legacy_target_cls:
            mlflow.log_metric(f'precision_{clz}',ex[4][clz]['precision'])
            mlflow.log_metric(f'recall_{clz}',ex[4][clz]['recall'])
            mlflow.log_metric(f'f1_score_{clz}',ex[4][clz]['f1-score'])

2026/04/29 19:01:47 INFO mlflow.tracking.fluent: Experiment with name 'Log_Classification' does not exist. Creating a new experiment.

🏃 View run svm at: http://localhost:5000/#/experiments/2/runs/f49144fe7bf54da0b219a84cdb7f9e21
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run random_forest at: http://localhost:5000/#/experiments/2/runs/04052899446d41cf8ae9d5b2780c9a00
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run logistic_regression at: http://localhost:5000/#/experiments/2/runs/1e1a1442ac9144829aeff97fab96a3c9
🧪 View experiment at: http://localhost:5000/#/experiments/2
🏃 View run gaussian_nb at: http://localhost:5000/#/experiments/2/runs/c7a8c72db6e64dacb93356c48aefd28c
🧪 View experiment at: http://localhost:5000/#/experiments/2

In [38]:
# from the anlytics SVM seems to be the best performing model
analytics[0]

['svm',
 {'C': 2, 'kernel': 'poly'},
 0.9984990566303399,
 GridSearchCV(cv=5, estimator=SVC(),
              param_grid={'C': [1, 2, 3, 4, 5, 7, 10, 11],
                          'kernel': ['linear', 'poly', 'rbf', 'sigmoid']}),
 {'Critical Error': {'precision': 0.9795918367346939,
   'recall': 1.0,
   'f1-score': 0.9896907216494846,
   'support': 48.0},
  'Error': {'precision': 1.0,
   'recall': 0.9787234042553191,
   'f1-score': 0.989247311827957,
   'support': 47.0},
  'HTTP Status': {'precision': 1.0,
   'recall': 1.0,
   'f1-score': 1.0,
   'support': 304.0},
  'Resource Usage': {'precision': 1.0,
   'recall': 1.0,
   'f1-score': 1.0,
   'support': 49.0},
  'Security Alert': {'precision': 1.0,
   'recall': 1.0,
   'f1-score': 1.0,
   'support': 123.0},
  'accuracy': 0.9982486865148862,
  'macro avg': {'precision': 0.9959183673469388,
   'recall': 0.9957446808510639,
   'f1-score': 0.9957876066954883,
   'support': 571.0},
  'weighted avg': {'precision': 0.9982844276064191,
   'recall': 0.9982486865148862,
   'f1-score': 0.9982482982400863,
   'support': 571.0}}]

In [40]:
import joblib

model = SVC(C=2,kernel='poly',probability=True)
model.fit(X_train,y_train)
joblib.dump(model,'./models/log_clf.joblib')

['./models/log_clf.joblib']